-define(PLAIN,{<<"content-type">>,<<"text/plain">>}).
-define(XHTML,{<<"content-type">>,<<"application/xhtml+xml">>}).
-define(XMLNS,{xmlns,"http://www.w3.org/1999/xhtml"}).
-define(CHARSET,{charset,"UTF-8"}).
